apiVersion: v1
kind: Service
metadata:
  labels:
    app: salt
  name: salt
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 15151
    name: http
  selector:
    app: salt
  type: LoadBalancer
