apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backup-api-hitter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: backup
    spec:
      nodeSelector:
        cluster: default-pool
      containers:
      - name: backup-api-hitter
        image: gcr.io/cs193s-cqiaoben/backup:$1
        ports:
        - containerPort: 12345
        env:
        - name: SQL_HOST
          value: '$2'
        - name: SALT_HOST
          value: '$3'
