apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: salt
  annotations:
    federation.kubernetes.io/deployment-preferences: |
        {
            "rebalance": false,
            "clusters": {
                "cluster-asia-east1-a": {
                    "minReplicas": 1,
                    "maxReplicas": 1,
                    "weight": 1
                },
                "cluster-europe-west1-b": {
                    "minReplicas": 1,
                    "maxReplicas": 1,
                    "weight": 1
                },
                "cluster-us-east1-b": {
                    "minReplicas": 1,
                    "maxReplicas": 1,
                    "weight": 1
                }
            }
        }
spec:
  replicas: 4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: salt
    spec:
      containers:
        - name: salt
          image: gcr.io/cs193s-cqiaoben-3-20/salt:$1
          ports:
          - containerPort: 15151
            hostPort: 11111
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
        - name: kubectl
          image: gcr.io/cs193s-cqiaoben-3-20/kubectl:v3.24.12.8
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
          imagePullPolicy: Always
          command: ['kubectl', 'proxy', '--port=8001', '--context=federation']

