apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: salt-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: salt
    spec:
      nodeSelector:
        cluster: salt-pool
      containers:
      - name: salt
        image: gcr.io/cs193s-cqiaoben/salt:$1
        ports:
        - containerPort: 55554
        env:
        - name: REPLAY_HOST
          value: '$2'
