apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: salt-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: salt
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: salt
        image: gcr.io/spry-bus-159905/salt:$1
        ports:
        - containerPort: 55554
        env:
        - name: REPLAY_HOST
          value: '$2'
