#!/bin/bash

docker build --no-cache -t gcr.io/cs193s-cqiaoben-3-20/backup:$1 -f dockerfile/backup_api_hitter.docker .
gcloud docker -- push gcr.io/cs193s-cqiaoben-3-20/backup:$1

rm -f temp.yaml

FILE=$(cat yamlfile/backup_node.yaml)
FILE1=${FILE/\$1/$1}
FILE2=${FILE1/\$2/$2}
FILE3=${FILE2/\$3/$3}
echo "$FILE3" > temp.yaml
kubectl create -f ./temp.yaml

