#!/bin/bash

docker build --no-cache -t gcr.io/cs193s-cqiaoben/api-hitter:$1 -f dockerfile/api_hitter.docker .
gcloud docker push gcr.io/cs193s-cqiaoben/api-hitter:$1

rm -f temp.yaml

FILE=$(cat yamlfile/api_node.yaml)
FILE1=${FILE/\$1/$1}
FILE2=${FILE1/\$2/$2}
FILE3=${FILE2/\$3/$3}
FILE4=${FILE3/\$4/$4}
echo "$FILE4" > temp.yaml
kubectl create -f ./temp.yaml
